[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
solc_version = "0.8.24"

[fuzz]
runs = 256

[invariant]
runs = 128
depth = 32
